# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enterform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(390, 155)
        Form.setMinimumSize(QtCore.QSize(390, 155))
        Form.setMaximumSize(QtCore.QSize(390, 155))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/pass_cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label_img = QtWidgets.QLabel(Form)
        self.label_img.setGeometry(QtCore.QRect(30, 30, 81, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_img.sizePolicy().hasHeightForWidth())
        self.label_img.setSizePolicy(sizePolicy)
        self.label_img.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_img.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_img.setText("")
        self.label_img.setPixmap(QtGui.QPixmap(":/icons/icons/pass_cloud.png"))
        self.label_img.setScaledContents(True)
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 30, 191, 82))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_enter = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_enter.setObjectName("label_enter")
        self.verticalLayout.addWidget(self.label_enter)
        self.line_enter = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.line_enter.setAutoFillBackground(False)
        self.line_enter.setInputMask("")
        self.line_enter.setMaxLength(25)
        self.line_enter.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_enter.setObjectName("line_enter")
        self.verticalLayout.addWidget(self.line_enter)
        self.btn_enter = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_enter.setObjectName("btn_enter")
        self.verticalLayout.addWidget(self.btn_enter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вход"))
        self.label_enter.setText(_translate("Form", "Введите пароль"))
        self.btn_enter.setText(_translate("Form", "Вход"))
import rec_rc
