# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 523)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/pass_cloud.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line_find = QtWidgets.QLineEdit(self.centralwidget)
        self.line_find.setMinimumSize(QtCore.QSize(160, 0))
        self.line_find.setMaximumSize(QtCore.QSize(160, 16777215))
        self.line_find.setObjectName("line_find")
        self.verticalLayout_2.addWidget(self.line_find)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 5))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_list = QtWidgets.QLabel(self.centralwidget)
        self.label_list.setObjectName("label_list")
        self.verticalLayout_2.addWidget(self.label_list)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(160, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(160, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_7.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_create = QtWidgets.QPushButton(self.centralwidget)
        self.btn_create.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_create.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_create.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create.setIcon(icon1)
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout_3.addWidget(self.btn_create)
        self.btn_read = QtWidgets.QPushButton(self.centralwidget)
        self.btn_read.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_read.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_read.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_read.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_read.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/open-book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_read.setIcon(icon2)
        self.btn_read.setObjectName("btn_read")
        self.horizontalLayout_3.addWidget(self.btn_read)
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_edit.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_edit.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_edit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/copy-writing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon3)
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout_3.addWidget(self.btn_edit)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_save.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_save.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon4)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_3.addWidget(self.btn_save)
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_delete.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_delete.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-bin-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon5)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_3.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_title = QtWidgets.QPushButton(self.centralwidget)
        self.label_title.setMinimumSize(QtCore.QSize(0, 25))
        self.label_title.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_title.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_4.addWidget(self.label_title)
        self.btn_exit_create = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit_create.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_exit_create.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_exit_create.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_exit_create.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/delete_delete_exit_1577.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit_create.setIcon(icon6)
        self.btn_exit_create.setIconSize(QtCore.QSize(10, 10))
        self.btn_exit_create.setObjectName("btn_exit_create")
        self.horizontalLayout_4.addWidget(self.btn_exit_create)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_title = QtWidgets.QLineEdit(self.centralwidget)
        self.line_title.setToolTip("")
        self.line_title.setStatusTip("")
        self.line_title.setText("")
        self.line_title.setMaxLength(16)
        self.line_title.setReadOnly(False)
        self.line_title.setObjectName("line_title")
        self.verticalLayout.addWidget(self.line_title)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_link = QtWidgets.QPushButton(self.centralwidget)
        self.label_link.setMinimumSize(QtCore.QSize(0, 25))
        self.label_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_link.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.label_link.setObjectName("label_link")
        self.horizontalLayout_5.addWidget(self.label_link)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_link = QtWidgets.QLineEdit(self.centralwidget)
        self.line_link.setObjectName("line_link")
        self.verticalLayout.addWidget(self.line_link)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_login = QtWidgets.QPushButton(self.centralwidget)
        self.label_login.setMinimumSize(QtCore.QSize(0, 25))
        self.label_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_login.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.label_login.setObjectName("label_login")
        self.horizontalLayout_6.addWidget(self.label_login)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        self.line_login.setObjectName("line_login")
        self.verticalLayout.addWidget(self.line_login)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_password = QtWidgets.QPushButton(self.centralwidget)
        self.label_password.setMinimumSize(QtCore.QSize(0, 25))
        self.label_password.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_password.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_2.addWidget(self.label_password)
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_generate.sizePolicy().hasHeightForWidth())
        self.btn_generate.setSizePolicy(sizePolicy)
        self.btn_generate.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_generate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_generate.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_generate.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_generate.setIcon(icon7)
        self.btn_generate.setObjectName("btn_generate")
        self.horizontalLayout_2.addWidget(self.btn_generate)
        self.btn_settings = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_settings.sizePolicy().hasHeightForWidth())
        self.btn_settings.setSizePolicy(sizePolicy)
        self.btn_settings.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_settings.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.btn_settings.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/customer-support.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon8)
        self.btn_settings.setObjectName("btn_settings")
        self.horizontalLayout_2.addWidget(self.btn_settings)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setObjectName("line_password")
        self.verticalLayout.addWidget(self.line_password)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_additionally = QtWidgets.QPushButton(self.centralwidget)
        self.label_additionally.setMinimumSize(QtCore.QSize(0, 25))
        self.label_additionally.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_additionally.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A0A0A0\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #F0F0F0;    \n"
"}\n"
"")
        self.label_additionally.setObjectName("label_additionally")
        self.horizontalLayout.addWidget(self.label_additionally)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.text_additionally = QtWidgets.QTextEdit(self.centralwidget)
        self.text_additionally.setObjectName("text_additionally")
        self.verticalLayout.addWidget(self.text_additionally)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 750, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.current_card = QtWidgets.QAction(MainWindow)
        self.current_card.setObjectName("current_card")
        self.all_card = QtWidgets.QAction(MainWindow)
        self.all_card.setObjectName("all_card")
        self.actionprint = QtWidgets.QAction(MainWindow)
        self.actionprint.setObjectName("actionprint")
        self.menu.addAction(self.current_card)
        self.menu.addAction(self.all_card)
        self.menu.addSeparator()
        self.menu.addAction(self.actionprint)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Хранение паролей"))
        self.line_find.setPlaceholderText(_translate("MainWindow", "Поиск..."))
        self.label_list.setText(_translate("MainWindow", "Список"))
        self.label_title.setText(_translate("MainWindow", " Название "))
        self.label_link.setText(_translate("MainWindow", " Ссылка "))
        self.label_login.setText(_translate("MainWindow", " Логин "))
        self.label_password.setText(_translate("MainWindow", " Пароль "))
        self.label_additionally.setText(_translate("MainWindow", " Дополнительно "))
        self.text_additionally.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "Экспорт"))
        self.current_card.setText(_translate("MainWindow", "Экспортировать текущую карточку"))
        self.all_card.setText(_translate("MainWindow", "Экспортировать все"))
        self.actionprint.setText(_translate("MainWindow", "print"))
import rec_rc
